bodega/apps/home/urls.py
from django.conf.urls import url

from django.views.generic import TemplateView
from .views import InicioView

urlpatterns = [
    url(r'^$', InicioView.as_view(), name="inicio"),
    url(r'^home$', TemplateView.as_view(template_name='home.html'), name="show_home"),
]

bodega/apps/recursos/urls.py
from django.conf.urls import include, url
from apps.recursos import views,forms


urlpatterns = [
    url(r'^registrar-categoria$', views.RegistrarCategoria.as_view(), name="registrar_categoria"),
    url(r'^editar-categoria/(?P<pk>\d+)$', views.EditarCategoria.as_view(), name="editar_categoria"),
    url(r'^registrar-marcas', views.RegistrarMarca.as_view(), name="registrar_marca"),
    url(r'^editar-marcas/(?P<pk>\d+)$', views.EditarMarca.as_view(), name="editar_marca"),
    url(r'^registrar-recurso', views.RegistrarRecurso.as_view(), name="registrar_recurso"),
    url(r'^editar-recurso/(?P<pk>\d+)$', views.EditarRecurso.as_view(), name="editar_recurso"),
    url(r'^detalle-recurso/(?P<pk>\d+)$', views.DetalleRecurso.as_view(), name="detalle_recurso"),
    url(r'^retirar-recurso/(?P<pk>\d+)$', views.retirar_recurso, name="retirar_recurso"),
    url(r'^asignar-varios', views.AsignarRecursoVarios.as_view(), name="asignar_varios_recursos"),
    url(r'^trasladar', views.TrasladarRecursos.as_view(), name="trasladar_recursos"),
    url(r'^ajax/obtener_recursos/$', views.obtener_recursos, name='obtener_recursos'),
]

bodega/apps/usuarios/urls.py
from django.conf.urls import  url
from apps.usuarios import views
from django.contrib.auth import views as auth_views



urlpatterns = [
    url(r'^password_change$', auth_views.password_change,{'post_change_redirect': 'usuarios:password_change_done' }, name="password_change"),
    url(r'^password_change_done$', auth_views.password_change_done, name='password_change_done'),

    url(r'^registrar$', views.RegistrarUsuario.as_view(), name="registrar_usuario"),
    url(r'^editar/(?P<pk>\d+)$', views.EditarUsuario.as_view(), name="editar_usuario"),
    url(r'^listar$', views.ListarUsuarios.as_view(), name="lista_usuarios"),
    url(r'^dashboard$', views.InicioUsuario.as_view(), name="dashboard"),

    url(r'^login$', views.Login.as_view(), name="login"),
    url(r'^logout$', views.Logout, name="logout"),


]

bodega/bodega/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^usuarios/', include('apps.usuarios.urls', namespace='usuarios')),
    url(r'^recursos/', include('apps.recursos.urls', namespace='recursos')),
    url(r'^personal/', include('apps.personal.urls', namespace='personal')),
    url(r'^', include('django.contrib.auth.urls')),
    url(r'^', include('apps.home.urls', namespace='home')),
    url(r'^select2/', include('django_select2.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bodega/apps/usuarios/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from bodega import variables_choices
# Create your models here.


class User(AbstractUser):

    identificacion = models.CharField(max_length=30)
    telefono_fijo = models.CharField(max_length=15,blank=True)
    telefono_celular = models.CharField(max_length=15,blank=True)
    foto = models.ImageField(upload_to='media', blank=True, null=True, )
    direccion = models.CharField(max_length=100)
    cargo = models.CharField(max_length=50, choices=variables_choices.CARGOS, verbose_name='Perfil')
    genero = models.CharField(max_length=50, choices=variables_choices.GENEROS, verbose_name="Género")


    def __str__(self):
        return '%s %s' % (self.last_name, self.first_name)

    # Función que devuelve la pagina html del dashboard dependiendo del tipo de usuario
    def obtener_pagina_dashboard(self):
        if self.cargo == 'Administrador':
            return "inicio_administrador.html"

        return "inicio_administrador.html"

#Funcion que devuelve los datos para el dashboard dependiendo del tipo de usuario
    def datos_dashboard(self):
        from apps.personal.models import Personal
        from apps.recursos.models import Recurso
        datos = {}
        datos['lista_personal']= Personal.objects.all()
        recursos_asignados = Recurso.objects.filter(asignaciones__esta_asignado=True).values_list('id')
        datos['lista_recursos'] = Recurso.objects.exclude(id__in=recursos_asignados) #recursos sin asignar
        return datos

bodega/templates/menus/base_menu.html
{% load staticfiles %}
<!-- Left side column. contains the sidebar -->
{% if user.is_authenticated %}
    {% url 'usuarios:dashboard' as dashboard %}
{% else %}
    {% url 'home:inicio' as dashboard %}
{% endif %}
  <aside class="main-sidebar">
    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">
      <!-- Sidebar user panel -->
      <div class="user-panel">
        <div class="pull-left image">
            {% if user.foto != "" and user.foto != None and user.foto != "media/profile.png" %}
          <img src="{{ MEDIA_URL }}{{ user.foto }}" class="img-circle" alt="User Image">
            {% else %}
                <img src="{% static 'img/profile.png' %}" class="img-circle" alt="User Image">
            {% endif %}
        </div>
        <div class="pull-left info">
          <p>{{ user.get_full_name | capfirst}}</p>
          <small>{{ user.get_cargo_display }}</small>
        </div>
      </div>

      <!-- sidebar menu: : style can be found in sidebar.less -->
      <ul class="sidebar-menu" data-widget="tree">
        <li class="header">Navegacion principal</li>
          <li>
          <a href="{{dashboard}}">
            <i class="fa fa-dashboard"></i> <span>Danshboard</span>
          </a>
        </li>
        {% if user.cargo == 'Administrador' %}
            {% include 'menus/administrador/usuarios.html' %}
            {% include 'menus/administrador/personal_menu.html' %}
            {% include 'menus/recursos_menu.html' %}

          {% endif %}

      </ul>
    </section>
    <!-- /.sidebar -->
  </aside>

bodega/templates/menus/recursos_menu.html
{% url 'recursos:registrar_categoria' as categoria_registro %}
{% url 'recursos:registrar_marca' as marca_registro %}
{% url 'recursos:registrar_recurso' as recurso_registro %}
{% url 'recursos:asignar_varios_recursos' as asignar_recurso %}
{% url 'recursos:trasladar_recursos' as trasladar_recursos %}

<li class="treeview {% if 'recursos' in request.path   %}active{% endif %}">
          <a href="#">
            <i class="fa fa-cubes"></i> <span>Recursos</span>
            <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
          </a>
          <ul class="treeview-menu">
            <li {% if categoria_registro in request.path %} class="active" {% endif %} >
        	<a href="{{ categoria_registro }}"><i class="fa fa-circle-o"></i> Gestionar categorías</a>
            </li>
          <li {% if marca_registro in request.path %} class="active" {% endif %} >
        	<a href="{{ marca_registro }}"><i class="fa fa-circle-o"></i> Gestionar marcas</a>
            </li>
          <li {% if recurso_registro in request.path %} class="active" {% endif %} >
        	<a href="{{ recurso_registro }}"><i class="fa fa-circle-o"></i> Gestionar recursos </a>
            </li>
          <li {% if asignar_recurso in request.path %} class="active" {% endif %} >
        	<a href="{{ asignar_recurso }}"><i class="fa fa-circle-o"></i> Asignar recursos </a>
            </li>
          <li {% if trasladar_recursos in request.path %} class="active" {% endif %} >
        	<a href="{{ trasladar_recursos }}"><i class="fa fa-circle-o"></i> Trasladar recursos </a>
            </li>

          </ul>
        </li>