bodega/apps/personal/urls.py
from django.conf.urls import include, url
from apps.personal import views,forms


urlpatterns = [
    url(r'^registrar$', views.RegistrarPersonal.as_view(), name="registrar_personal"),
    url(r'^editar/(?P<pk>\d+)$', views.EditarPersonal.as_view(), name="editar_personal"),
    url(r'^listar$', views.ListarPersonal.as_view(), name="lista_personal"),
    url(r'^ver-recursos/(?P<pk>\d+)$', views.VerRecursos.as_view(), name="ver_recursos_personal"),
]

bodega/apps/recursos/urls.py
from django.conf.urls import include, url
from apps.recursos import views,forms


urlpatterns = [
    url(r'^registrar-categoria$', views.RegistrarCategoria.as_view(), name="registrar_categoria"),
    url(r'^editar-categoria/(?P<pk>\d+)$', views.EditarCategoria.as_view(), name="editar_categoria"),
    url(r'^registrar-marcas', views.RegistrarMarca.as_view(), name="registrar_marca"),
    url(r'^editar-marcas/(?P<pk>\d+)$', views.EditarMarca.as_view(), name="editar_marca"),
    url(r'^registrar-recurso', views.RegistrarRecurso.as_view(), name="registrar_recurso"),
    url(r'^editar-recurso/(?P<pk>\d+)$', views.EditarRecurso.as_view(), name="editar_recurso"),
    url(r'^detalle-recurso/(?P<pk>\d+)$', views.DetalleRecurso.as_view(), name="detalle_recurso"),
    url(r'^retirar-recurso/(?P<pk>\d+)$', views.retirar_recurso, name="retirar_recurso"),
    url(r'^asignar-varios', views.AsignarRecursoVarios.as_view(), name="asignar_varios_recursos"),
    url(r'^trasladar', views.TrasladarRecursos.as_view(), name="trasladar_recursos"),
    url(r'^ajax/obtener_recursos/$', views.obtener_recursos, name='obtener_recursos'),
]

bodega/apps/usuarios/urls.py
from django.conf.urls import  url
from apps.usuarios import views
from django.contrib.auth import views as auth_views



urlpatterns = [
    url(r'^password_change$', auth_views.password_change,{'post_change_redirect': 'usuarios:password_change_done' }, name="password_change"),
    url(r'^password_change_done$', auth_views.password_change_done, name='password_change_done'),

    url(r'^registrar$', views.RegistrarUsuario.as_view(), name="registrar_usuario"),
    url(r'^editar/(?P<pk>\d+)$', views.EditarUsuario.as_view(), name="editar_usuario"),
    url(r'^listar$', views.ListarUsuarios.as_view(), name="lista_usuarios"),
    url(r'^dashboard$', views.InicioUsuario.as_view(), name="dashboard"),

    url(r'^login$', views.Login.as_view(), name="login"),
    url(r'^logout$', views.Logout, name="logout"),


]

bodega/bodega/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^usuarios/', include('apps.usuarios.urls', namespace='usuarios')),
    url(r'^recursos/', include('apps.recursos.urls', namespace='recursos')),
    url(r'^personal/', include('apps.personal.urls', namespace='personal')),
    url(r'^', include('django.contrib.auth.urls')),
    url(r'^', include('apps.home.urls', namespace='home')),
    url(r'^select2/', include('django_select2.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bodega/apps/personal/models.py
from django.db import models
from bodega import variables_choices
# Create your models here.


class Personal(models.Model):
    nombre = models.CharField(max_length=100)
    apellidos = models.CharField(max_length=100)
    identificacion = models.CharField(max_length=30,unique=True)
    genero = models.CharField(max_length=50, choices=variables_choices.GENEROS, verbose_name="Género")
    telefono_fijo = models.CharField(max_length=15, blank=True)
    telefono_celular = models.CharField(max_length=15, blank=True)
    direccion = models.CharField(max_length=100,blank=True)
    email= models.EmailField()

    def __str__(self):
        return '%s %s' % (self.nombre, self.apellidos)

    def obtener_recursos_asignados(self):
        from apps.recursos.models import  Recurso
        return Recurso.objects.filter(asignaciones__esta_asignado=True,asignaciones__persona=self)

bodega/apps/personal/forms.py
from django import forms
from django_select2.forms import ModelSelect2MultipleWidget, Select2Widget, ModelSelect2Widget, Select2MultipleWidget
from .models import *
from apps.usuarios.models import User


class PersonalForm(forms.ModelForm):
    class Meta:
        model = Personal
        fields= '__all__'

bodega/apps/personal/views.py
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse_lazy
from django.views.generic import ListView, TemplateView, FormView,View
from django.views.generic.edit import CreateView, UpdateView
from django.views.generic.detail import DetailView
from django.contrib.auth.mixins import LoginRequiredMixin

from django.shortcuts import render, redirect, get_object_or_404
from .models import *
from .forms import *
# Create your views here.


class RegistrarPersonal(LoginRequiredMixin,SuccessMessageMixin,CreateView):
    model = Personal
    form_class = PersonalForm
    template_name = 'personal.html'
    success_url = reverse_lazy('personal:registrar_personal')
    success_message = "Se ha registrado exitosamente el personal "

    def get_context_data(self, **kwargs):
        context = super(RegistrarPersonal,self).get_context_data()
        context['titulo'] = 'Registrar personal'
        return context


class EditarPersonal(LoginRequiredMixin,SuccessMessageMixin,UpdateView):
    model = Personal
    form_class = PersonalForm
    template_name = 'personal.html'
    success_url = reverse_lazy('personal:lista_personal')
    success_message = "Se ha editado exitosamente el personal "

    def get_context_data(self, **kwargs):
        context = super(EditarPersonal,self).get_context_data()
        context['titulo'] = 'Editar personal'
        return context



class ListarPersonal(LoginRequiredMixin,ListView):
    model = Personal
    template_name = 'lista_personal.html'
    context_object_name = "lista_personal"


class VerRecursos(LoginRequiredMixin,DetailView):
    model = Personal
    template_name = 'lista_recursos_personal.html'
    context_object_name = "personal"

bodega/apps/personal/templates/lista_personal.html
{% extends "base.html" %}
{% load staticfiles %}
{% load bootstrap3 %}

{% block titulo %}
    Listar personal
{% endblock titulo %}
{% block css %}
{% endblock %}
{% block titulo_pagina %}
    Listar personal
{% endblock titulo_pagina %}

{% block miga_pan %}
    <li class="breadcrumb-item active">Inicio</li>
{% endblock miga_pan %}



{% block contenido_pagina %}

    <div class="row">
        <div class="col-lg-12 ">
            <!-- Default box -->
            <div class="box box-success">
                <div class="box-header">
                    <h3 class="box-title">Lista del personal</h3>
                </div>
                <!-- /.box-header -->
                <div class="box-body">
                    <table id="example1" class="table table-bordered table-striped dataTable">
                        <thead>
                        <tr>
                            <th>ID</th>
                            <th>Apellio</th>
                            <th>Nombre</th>
                            <th>Email</th>
                            <th>Opciones</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for personal in lista_personal %}
                            <tr>
                                <td>{{ personal.identificacion }}</td>
                                <td>{{ personal.apellidos }}</td>
                                <td>{{ personal.nombre }}</td>
                                <td>{{ personal.email }}</td>
                                <td>
                                    <a class="btn btn-warning" href="{% url 'personal:editar_personal' personal.pk %}">Editar</a>
                                    <a class="btn btn-primary" href="{% url 'personal:ver_recursos_personal' personal.pk %}">Ver recursos</a>

                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
                <!-- /.box-body -->
            </div>

        </div>
    </div>



{% endblock %}
{% block js %}

{% endblock %}
    

bodega/apps/personal/templates/lista_recursos_personal.html
{% extends "base.html" %}
{% load staticfiles %}
{% load bootstrap3 %}

{% block titulo %}
    listar de recursos {{ personal }}
{% endblock titulo %}
{% block css %}
{% endblock %}
{% block titulo_pagina %}
    listar de recursos {{ personal }}
{% endblock titulo_pagina %}

{% block miga_pan %}
    <li class="breadcrumb-item active">Inicio</li>
{% endblock miga_pan %}
{% block regreso %}
    <li><a class="btn btn-sm btn-primary" href="{% url 'usuarios:dashboard' %}">Regresar</a></li>
{% endblock regreso %}



{% block contenido_pagina %}

    <div class="row">
        <div class="col-lg-12 ">
            <!-- Default box -->
            <div class="box box-success">
                <div class="box-header">
                    <h3 class="box-title">Lista del recursos</h3>
                </div>
                <!-- /.box-header -->
                <div class="box-body">
                    <table id="example1" class="table table-bordered table-striped dataTable">
                        <thead>
                        <tr>
                            <th>Nombre</th>
                            <th>Descripción</th>
                            <th>Marca</th>
                            <th>Categoría</th>
                            <th>Opciones</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for recurso in personal.obtener_recursos_asignados %}
                            <tr>
                                <td>{{ recurso }}</td>
                                <td>{{ recurso.descripcion }}</td>
                                <td>{{ recurso.marca }}</td>
                                <td>{{ recurso.categoria }}</td>
                                <td>
                                    <a class="btn btn-info" href="{% url 'recursos:detalle_recurso' recurso.pk %}">Detalles</a>
                                    <a data-toggle="modal" data-target="#modal-votar" href="#"
                                       data-url="{% url 'recursos:retirar_recurso' recurso.pk %}" data-text="{{ recurso.nombre }}"
                                       class="retiro btn btn-warning">Retirar</a>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
                <!-- /.box-body -->
            </div>

        </div>
    </div>
    <div class="modal fade" id="modal-votar">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title">Retirar recurso</h4>
                </div>
                <div class="modal-body">
                    <p>Esta seguro que desea retira el recurso <label class="Text-recurso"></label> </p>
                </div>
                <div class="modal-footer">

                    <button type="button" class="btn btn-default pull-left" data-dismiss="modal">Cancelar</button>
                    <a id="confirmar-retiro" href="" class="btn btn-danger">Retirar</a>
                </div>
            </div>
            <!-- /.modal-content -->
        </div>
        <!-- /.modal-dialog -->
    </div>



{% endblock %}
{% block js %}
    <script>
        $(".retiro").on('click',function(e){
            var url = $(this).attr('data-url');
            var texto = $(this).data('text');
            $("#confirmar-retiro").attr('href',url);
            $(".Text-recurso").text(texto);
        });
    </script>
{% endblock %}
    

bodega/apps/personal/templates/personal.html
{% extends "base.html" %}
{% load staticfiles %}
{% load bootstrap3 %}

{% block titulo %}
    {{ titulo }}
{% endblock titulo %}
{% block css %}
{% endblock %}
{% block titulo_pagina %}
    {{ titulo }}
{% endblock titulo_pagina %}

{% block miga_pan %}
    <li class="breadcrumb-item active">Inicio</li>
{% endblock miga_pan %}
{% block regreso %}
    <li><a class="btn btn-sm btn-primary" href="{% url 'usuarios:dashboard' %}">Regresar</a></li>
{% endblock regreso %}

{% block contenido_pagina %}

    <div class="row">
        <div class="col-lg-6 ">
            <!-- Default box -->
            <div class="box box-success">
                <div class="box-header with-border">
                    <h3 class="box-title">{{ titulo }}</h3>
                </div>
                <!-- /.box-header -->
                <!-- form start -->
                <form role="form" method="post" enctype="multipart/form-data">{% csrf_token %}
                    <div class="box-body">
                        <div class="form-group">
                            {% bootstrap_form form %}
                        </div>

                    </div>
                    <!-- /.box-body -->

                    <div class="box-footer">
                        <button type="submit" class="btn btn-primary">Registrar</button>
                        <a href="{% url  'usuarios:lista_usuarios'%}" class="btn btn-default">Cancelar</a>
                    </div>
                </form>
            </div>
            <!-- /.box -->

        </div>
    </div>



{% endblock %}
{% block js %}

{% endblock %}
    