bodega/apps/home/urls.py
from django.conf.urls import url

from django.views.generic import TemplateView
from .views import InicioView

urlpatterns = [
    url(r'^$', InicioView.as_view(), name="inicio"),
    url(r'^home$', TemplateView.as_view(template_name='home.html'), name="show_home"),
]

bodega/apps/personal/urls.py
from django.conf.urls import include, url
from apps.personal import views,forms


urlpatterns = [
    url(r'^registrar$', views.RegistrarPersonal.as_view(), name="registrar_personal"),
    url(r'^editar/(?P<pk>\d+)$', views.EditarPersonal.as_view(), name="editar_personal"),
    url(r'^listar$', views.ListarPersonal.as_view(), name="lista_personal"),
    url(r'^ver-recursos/(?P<pk>\d+)$', views.VerRecursos.as_view(), name="ver_recursos_personal"),
]

bodega/apps/recursos/urls.py
from django.conf.urls import include, url
from apps.recursos import views,forms


urlpatterns = [
    url(r'^registrar-categoria$', views.RegistrarCategoria.as_view(), name="registrar_categoria"),
    url(r'^editar-categoria/(?P<pk>\d+)$', views.EditarCategoria.as_view(), name="editar_categoria"),
    url(r'^registrar-marcas', views.RegistrarMarca.as_view(), name="registrar_marca"),
    url(r'^editar-marcas/(?P<pk>\d+)$', views.EditarMarca.as_view(), name="editar_marca"),
    url(r'^registrar-recurso', views.RegistrarRecurso.as_view(), name="registrar_recurso"),
    url(r'^editar-recurso/(?P<pk>\d+)$', views.EditarRecurso.as_view(), name="editar_recurso"),
    url(r'^detalle-recurso/(?P<pk>\d+)$', views.DetalleRecurso.as_view(), name="detalle_recurso"),
    url(r'^retirar-recurso/(?P<pk>\d+)$', views.retirar_recurso, name="retirar_recurso"),
    url(r'^asignar-varios', views.AsignarRecursoVarios.as_view(), name="asignar_varios_recursos"),
    url(r'^trasladar', views.TrasladarRecursos.as_view(), name="trasladar_recursos"),
    url(r'^ajax/obtener_recursos/$', views.obtener_recursos, name='obtener_recursos'),
]

bodega/apps/usuarios/urls.py
from django.conf.urls import  url
from apps.usuarios import views
from django.contrib.auth import views as auth_views



urlpatterns = [
    url(r'^password_change$', auth_views.password_change,{'post_change_redirect': 'usuarios:password_change_done' }, name="password_change"),
    url(r'^password_change_done$', auth_views.password_change_done, name='password_change_done'),

    url(r'^registrar$', views.RegistrarUsuario.as_view(), name="registrar_usuario"),
    url(r'^editar/(?P<pk>\d+)$', views.EditarUsuario.as_view(), name="editar_usuario"),
    url(r'^listar$', views.ListarUsuarios.as_view(), name="lista_usuarios"),
    url(r'^dashboard$', views.InicioUsuario.as_view(), name="dashboard"),

    url(r'^login$', views.Login.as_view(), name="login"),
    url(r'^logout$', views.Logout, name="logout"),


]

bodega/bodega/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^usuarios/', include('apps.usuarios.urls', namespace='usuarios')),
    url(r'^recursos/', include('apps.recursos.urls', namespace='recursos')),
    url(r'^personal/', include('apps.personal.urls', namespace='personal')),
    url(r'^', include('django.contrib.auth.urls')),
    url(r'^', include('apps.home.urls', namespace='home')),
    url(r'^select2/', include('django_select2.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bodega/apps/usuarios/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from bodega import variables_choices
# Create your models here.


class User(AbstractUser):

    identificacion = models.CharField(max_length=30)
    telefono_fijo = models.CharField(max_length=15,blank=True)
    telefono_celular = models.CharField(max_length=15,blank=True)
    foto = models.ImageField(upload_to='media', blank=True, null=True, )
    direccion = models.CharField(max_length=100)
    cargo = models.CharField(max_length=50, choices=variables_choices.CARGOS, verbose_name='Perfil')
    genero = models.CharField(max_length=50, choices=variables_choices.GENEROS, verbose_name="Género")


    def __str__(self):
        return '%s %s' % (self.last_name, self.first_name)

    # Función que devuelve la pagina html del dashboard dependiendo del tipo de usuario
    def obtener_pagina_dashboard(self):
        if self.cargo == 'Administrador':
            return "inicio_administrador.html"

        return "inicio_administrador.html"

#Funcion que devuelve los datos para el dashboard dependiendo del tipo de usuario
    def datos_dashboard(self):
        from apps.personal.models import Personal
        from apps.recursos.models import Recurso
        datos = {}
        datos['lista_personal']= Personal.objects.all()
        recursos_asignados = Recurso.objects.filter(asignaciones__esta_asignado=True).values_list('id')
        datos['lista_recursos'] = Recurso.objects.exclude(id__in=recursos_asignados) #recursos sin asignar
        return datos

bodega/apps/usuarios/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm,UserChangeForm,PasswordChangeForm
from django_select2.forms import ModelSelect2MultipleWidget, Select2Widget, ModelSelect2Widget, Select2MultipleWidget
from .models import *





class UserForm(UserCreationForm):
    class Meta:
        model = User
        fields= ('username','email','identificacion','first_name','last_name','cargo','genero')
        widgets = {
            'cargo':Select2Widget,
            'genero': Select2Widget,
        }

    def __init__(self, *args, **kwargs):
        super(UserForm, self).__init__(*args, **kwargs)


class EditUserForm(forms.ModelForm):
    class Meta:
        model = User
        fields= ('first_name','last_name','telefono_fijo','telefono_celular','email','foto','cargo','genero')
        widgets = {
            'cargo': Select2Widget,
            'genero': Select2Widget,
        }

    def __init__(self, *args, **kwargs):
        super(EditUserForm, self).__init__(*args, **kwargs)


class LoginForm(forms.Form):


    username = forms.CharField(max_length = 50,
            widget=forms.TextInput(attrs ={
                    'id':'usernameInput',
                    'placeholder': 'Nombre de usuario',
                    'class':'form-control'
                }))
    password = forms.CharField(max_length = 50,
            widget = forms.TextInput(attrs = {
                    'type' : 'password',
                    'id':'passwordInput',
                    'placeholder': 'Contraseña',
                    'class':'form-control'
                }))

bodega/apps/usuarios/views.py
from django.contrib import messages
from django.core.urlresolvers import reverse_lazy
from django.views.generic import ListView, TemplateView, FormView,View
from django.views.generic.edit import CreateView, UpdateView

from django.contrib.auth.mixins import LoginRequiredMixin

from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render, redirect, get_object_or_404
from .models import *
from .forms import *

# Create your views here.


class RegistrarUsuario(LoginRequiredMixin,CreateView):
    model = User
    form_class = UserForm
    template_name = 'usuario.html'
    success_url = reverse_lazy('usuarios:lista_usuarios')

    def get_context_data(self, **kwargs):
        context = super(RegistrarUsuario,self).get_context_data()
        context['titulo'] = 'Registrar usuario'
        return context

    def form_valid(self, form):
        self.object=form.save()
        messages.add_message(self.request, messages.SUCCESS, "Se ha registrado exitosamente al usuario ")
        return super(RegistrarUsuario, self).form_valid(form)


class EditarUsuario(LoginRequiredMixin,UpdateView):
    model = User
    form_class = EditUserForm
    template_name = 'usuario.html'
    success_url = reverse_lazy('usuarios:lista_usuarios')
    context_object_name = 'usuario'

    def form_valid(self, form):
        self.object=form.save()
        messages.add_message(self.request, messages.SUCCESS, "Se ha editado exitosamente al usuario ")
        return super(EditarUsuario, self).form_valid(form)

    def get_context_data(self, **kwargs):
        context = super(EditarUsuario,self).get_context_data()
        context['titulo'] = 'Editar usuario'
        return context


class ListarUsuarios(LoginRequiredMixin,ListView):
    model = User
    template_name = 'lista_usuarios.html'
    context_object_name = "lista_usuarios"


class Login(FormView):
    form_class = LoginForm
    template_name = 'login.html'

    def get(self, request, *args, **kwargs):
        if self.request.user.is_authenticated:
            return redirect('usuarios:dashboard')
        return super(Login,self).get(request)

    def form_valid(self, form):
        mensaje = ""
        user = authenticate(username=form.cleaned_data['username'], password=form.cleaned_data['password'])
        if user is not None:
            if user.is_active:
                self.success_url = reverse_lazy('usuarios:dashboard')
                login(self.request, user)
                return super(Login, self).form_valid(form)
            else:
                mensaje = ("El usuario %s no esta activo") % (user.username)
        else:
            mensaje = "El usuario no existe o la contraseña es incorrecta"
        form.add_error('username', mensaje)
        return super(Login, self).form_invalid(form)

    def form_invalid(self, form):
        return super(Login, self).form_invalid(form)


def Logout(request):
    logout(request)
    return redirect(reverse_lazy('usuarios:login'))


class InicioUsuario(LoginRequiredMixin, TemplateView):

    def get_context_data(self, **kwargs):
        context = super(InicioUsuario, self).get_context_data(**kwargs)
        self.template_name = self.request.user.obtener_pagina_dashboard()
        context.update(self.request.user.datos_dashboard())
        return context

bodega/apps/usuarios/templates/inicio_administrador.html
{% extends "base.html" %}
{% load staticfiles %}
{% load bootstrap3 %}

{% block titulo %}
    Dashboard admin
{% endblock titulo %}
{% block css %}
{% endblock %}
{% block titulo_pagina %}
    Dashboard admin
{% endblock titulo_pagina %}

{% block miga_pan %}
    <li class="breadcrumb-item active">Inicio</li>
{% endblock miga_pan %}

{% block contenido_pagina %}

    <div class="row">
        <div class="col-lg-6 ">
            <!-- Default box -->
            <div class="box box-primary">
                <div class="box-header">
                    <h3 class="box-title">Lista de personal</h3>
                </div>
                <!-- /.box-header -->
                <div class="box-body">
                    <table id="example1" class="table table-bordered table-striped dataTable">
                        <thead>
                        <tr>
                            <th>ID</th>
                            <th>Nombre</th>

                            <th>Opciones</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for personal in lista_personal %}
                            <tr>
                                <td>{{ personal.identificacion }}</td>
                                <td>{{ personal.apellidos }} {{ personal.nombre }}</td>
                                <td>
                                    <a class="btn btn-warning" href="{% url 'personal:editar_personal' personal.pk %}">Editar</a>
                                    <a class="btn btn-primary" href="{% url 'personal:ver_recursos_personal' personal.pk %}">Ver recursos</a>

                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
                <!-- /.box-body -->
            </div>

        </div>
        <div class="col-lg-6 ">
            <!-- Default box -->
            <div class="box">
                <div class="box-header">
                    <h3 class="box-title">Recursos no asignados</h3>
                </div>
                <!-- /.box-header -->
                <div class="box-body">
                    <table id="example1" class="table table-bordered table-striped dataTable">
                        <thead>
                        <tr>
                            <th>Nombre</th>
                            <th>Descripción</th>
                            <th>Opciones</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for recurso in lista_recursos %}
                            <tr>
                                <td>{{ recurso }}</td>
                                <td>{{ recurso.descripcion }}</td>
                                <td>
                                    <a class="btn btn-info" href="{% url 'recursos:detalle_recurso' recurso.pk %}">Detalles</a>
                                    <a class="btn btn-warning" href="{% url 'recursos:editar_recurso' recurso.pk %}">Editar</a>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
                <!-- /.box-body -->
            </div>

        </div>

    </div>



{% endblock %}
{% block js %}

{% endblock %}
    

bodega/apps/usuarios/templates/lista_usuarios.html
{% extends "base.html" %}
{% load staticfiles %}
{% load bootstrap3 %}

{% block titulo %}
    listar usuarios
{% endblock titulo %}
{% block css %}
{% endblock %}
{% block titulo_pagina %}
    listar usuarios
{% endblock titulo_pagina %}

{% block miga_pan %}
    <li class="breadcrumb-item active">Inicio</li>
{% endblock miga_pan %}



{% block contenido_pagina %}

    <div class="row">
        <div class="col-lg-12 ">
            <!-- Default box -->
            <div class="box box-primary">
                <div class="box-header">
                    <h3 class="box-title">Lista de usuarios</h3>
                </div>
                <!-- /.box-header -->
                <div class="box-body">
                    <table id="example1" class="table table-bordered table-striped dataTable">
                        <thead>
                        <tr>
                            <th>ID</th>
                            <th>Usuario</th>
                            <th>Nombre</th>
                            <th>Estado</th>
                            <th>Email</th>
                            <th>Opciones</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for usuario in lista_usuarios %}
                            <tr>
                                <td>{{ usuario.pk }}</td>
                                <td>{{ usuario.username }}</td>
                                <td>{{ usuario.get_full_name }}</td>
                                <td>
                                    {% if usuario.is_active %}
                                        <span class="label label-success">Activo</span>
                                    {% else %}
                                        <span class="label label-danger">Inactivo</span>
                                    {% endif %}</td>
                                <td>{{ usuario.email }}</td>
                                <td>
                                    <a class="btn btn-warning" href="{% url 'usuarios:editar_usuario' usuario.pk %}">Editar</a>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
                <!-- /.box-body -->
            </div>

        </div>
    </div>



{% endblock %}
{% block js %}

{% endblock %}
    

bodega/apps/usuarios/templates/login.html
<!DOCTYPE html>
{% load staticfiles %}
{% load bootstrap3 %}
<html lang="es">
<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>AdminLTE 2 | Log in</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- Bootstrap 3.3.7 -->
    <link rel="stylesheet" href="{% static 'bower_components/bootstrap/dist/css/bootstrap.min.css' %}">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="{% static 'bower_components/font-awesome/css/font-awesome.min.css' %}">
    <!-- Ionicons -->
    <link rel="stylesheet" href="{% static 'bower_components/Ionicons/css/ionicons.min.css' %}">
    <!-- Theme style -->
    <link rel="stylesheet" href="{% static 'dist/css/AdminLTE.min.css' %}">
    <!-- iCheck -->
    <link rel="stylesheet" href="{% static 'plugins/iCheck/square/blue.css' %}">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->

    <!-- Google Font -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
</head>
<body class="hold-transition login-page">
<div class="login-box">
    <div class="login-logo">
        <a href="{% url 'home:inicio' %}"><b>Admin</b>LTE</a>
    </div>
    <!-- /.login-logo -->
    <div class="login-box-body">
        <p class="login-box-msg">Sign in to start your session</p>

        <form  method="post">{% csrf_token %}
            <div class="form-group has-feedback">
                {% bootstrap_field form.username %}
            </div>
            <div class="form-group has-feedback">
                {% bootstrap_field form.password %}
            </div>
            <div class="row">

                <!-- /.col -->
                <div class="col-xs-4">
                    <button type="submit" class="btn btn-primary btn-block btn-flat">Ingresar</button>
                </div>
                <!-- /.col -->
            </div>
        </form>



        <a href="{% url 'password_reset' %}">Olvide mi contraseña</a><br>

    </div>
    <!-- /.login-box-body -->
</div>
<!-- /.login-box -->

<!-- jQuery 3 -->
<script src="{% static 'bower_components/jquery/dist/jquery.min.js' %}"></script>
<!-- Bootstrap 3.3.7 -->
<script src="{% static 'bower_components/bootstrap/dist/js/bootstrap.min.js' %}"></script>
<!-- iCheck -->
<script src="{% static 'plugins/iCheck/icheck.min.js' %}"></script>

</body>
</html>

bodega/apps/usuarios/templates/usuario.html
{% extends "base.html" %}
{% load staticfiles %}
{% load bootstrap3 %}

{% block titulo %}
    {{ titulo }}
{% endblock titulo %}
{% block css %}
{% endblock %}
{% block titulo_pagina %}
    {{ titulo }}
{% endblock titulo_pagina %}

{% block miga_pan %}
    <li class="breadcrumb-item active">Inicio</li>
{% endblock miga_pan %}
{% block regreso %}
    <li><a class="btn btn-sm btn-primary" href="{% url 'usuarios:lista_usuarios' %}">Regresar</a></li>
{% endblock regreso %}

{% block contenido_pagina %}

    <div class="row">
        <div class="col-lg-6 ">
            <!-- Default box -->
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">{{ titulo }}</h3>
                </div>
                <!-- /.box-header -->
                <!-- form start -->
                <form role="form" method="post" enctype="multipart/form-data">{% csrf_token %}
                    <div class="box-body">
                        <div class="form-group">
                            {% bootstrap_form form %}
                        </div>

                    </div>
                    <!-- /.box-body -->

                    <div class="box-footer">
                        <button type="submit" class="btn btn-primary">Registrar</button>
                        <a href="{% url  'usuarios:lista_usuarios'%}" class="btn btn-default">Cancelar</a>
                    </div>
                </form>
            </div>
            <!-- /.box -->

        </div>
    </div>



{% endblock %}
{% block js %}

{% endblock %}
    