bodega/apps/recursos/urls.py
from django.conf.urls import include, url
from apps.recursos import views,forms


urlpatterns = [
    url(r'^registrar-categoria$', views.RegistrarCategoria.as_view(), name="registrar_categoria"),
    url(r'^editar-categoria/(?P<pk>\d+)$', views.EditarCategoria.as_view(), name="editar_categoria"),
    url(r'^registrar-marcas', views.RegistrarMarca.as_view(), name="registrar_marca"),
    url(r'^editar-marcas/(?P<pk>\d+)$', views.EditarMarca.as_view(), name="editar_marca"),
    url(r'^registrar-recurso', views.RegistrarRecurso.as_view(), name="registrar_recurso"),
    url(r'^editar-recurso/(?P<pk>\d+)$', views.EditarRecurso.as_view(), name="editar_recurso"),
    url(r'^detalle-recurso/(?P<pk>\d+)$', views.DetalleRecurso.as_view(), name="detalle_recurso"),
    url(r'^retirar-recurso/(?P<pk>\d+)$', views.retirar_recurso, name="retirar_recurso"),
    url(r'^asignar-varios', views.AsignarRecursoVarios.as_view(), name="asignar_varios_recursos"),
    url(r'^trasladar', views.TrasladarRecursos.as_view(), name="trasladar_recursos"),
    url(r'^ajax/obtener_recursos/$', views.obtener_recursos, name='obtener_recursos'),
]

bodega/apps/usuarios/urls.py
from django.conf.urls import  url
from apps.usuarios import views
from django.contrib.auth import views as auth_views



urlpatterns = [
    url(r'^password_change$', auth_views.password_change,{'post_change_redirect': 'usuarios:password_change_done' }, name="password_change"),
    url(r'^password_change_done$', auth_views.password_change_done, name='password_change_done'),

    url(r'^registrar$', views.RegistrarUsuario.as_view(), name="registrar_usuario"),
    url(r'^editar/(?P<pk>\d+)$', views.EditarUsuario.as_view(), name="editar_usuario"),
    url(r'^listar$', views.ListarUsuarios.as_view(), name="lista_usuarios"),
    url(r'^dashboard$', views.InicioUsuario.as_view(), name="dashboard"),

    url(r'^login$', views.Login.as_view(), name="login"),
    url(r'^logout$', views.Logout, name="logout"),


]

bodega/bodega/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^usuarios/', include('apps.usuarios.urls', namespace='usuarios')),
    url(r'^recursos/', include('apps.recursos.urls', namespace='recursos')),
    url(r'^personal/', include('apps.personal.urls', namespace='personal')),
    url(r'^', include('django.contrib.auth.urls')),
    url(r'^', include('apps.home.urls', namespace='home')),
    url(r'^select2/', include('django_select2.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bodega/apps/recursos/models.py
from django.db import models

# Create your models here.


class CategoriaRecurso(models.Model):

    nombre = models.CharField(max_length=100)

    def __str__(self):
        return self.nombre


class MarcaRecurso(models.Model):

    nombre = models.CharField(max_length=100)
    descripcion = models.TextField(verbose_name='Descripción')

    def __str__(self):
        return self.nombre


class Recurso(models.Model):

    nombre = models.CharField(max_length=100)
    descripcion = models.TextField(verbose_name='Descripción')
    codigo = models.CharField(max_length=30,verbose_name='Código',unique=True)
    marca = models.ForeignKey(MarcaRecurso,related_name='marca_recursos')
    categoria = models.ForeignKey(CategoriaRecurso, related_name='categoria_recursos',verbose_name='Categoría')

    def __str__(self):
        return '(%s) %s' % (self.codigo, self.nombre)


class AsignacionRecurso(models.Model):
    recurso = models.ForeignKey(Recurso,related_name='asignaciones')
    persona = models.ForeignKey('personal.Personal')
    esta_asignado = models.BooleanField(default=True)
    fecha = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-fecha']

bodega/apps/recursos/forms.py
from django import forms
from django_select2.forms import ModelSelect2MultipleWidget, Select2Widget, ModelSelect2Widget, Select2MultipleWidget
from .models import *
from apps.personal.models import Personal


class CategoriaForm(forms.ModelForm):
    class Meta:
        model = CategoriaRecurso
        fields= ('nombre',)


class MarcaForm(forms.ModelForm):
    class Meta:
        model = MarcaRecurso
        fields= ('nombre','descripcion')


class RecursoForm(forms.ModelForm):
    class Meta:
        model = Recurso
        fields = ('nombre','descripcion','codigo','marca','categoria')
        widgets= {
            'marca':Select2Widget,
            'categoria':Select2Widget,
        }


class AsignacionVariosRecursosForm(forms.Form):
    persona=forms.ModelChoiceField(queryset=Personal.objects.all(),widget=Select2Widget)
    recurso = forms.MultipleChoiceField(widget=Select2MultipleWidget)

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request')
        no_asignados = kwargs.pop('no_asignados')
        super(AsignacionVariosRecursosForm, self).__init__(*args, **kwargs)
        choices = []
        for item in Recurso.objects.filter(id__in=no_asignados):
            recurso_actual = (
                item.id, '(%s) %s' % (item.codigo, item.nombre)
            )
            choices.append(recurso_actual)
        self.fields['recurso'].choices= choices


class TrasladoRecursoForm(forms.Form):
    responsable = forms.ModelChoiceField(queryset=Personal.objects.all(), widget=Select2Widget)
    persona=forms.ModelChoiceField(queryset=Personal.objects.all(),widget=Select2Widget)
    recurso = forms.MultipleChoiceField(widget=Select2MultipleWidget)

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request')
        no_asignados = kwargs.pop('no_asignados')
        super(TrasladoRecursoForm, self).__init__(*args, **kwargs)
        choices = []
        for item in Recurso.objects.filter(asignaciones__esta_asignado=True):
            recurso_actual = (
                item.id, '(%s) %s' % (item.codigo, item.nombre)
            )
            choices.append(recurso_actual)
        self.fields['recurso'].choices= choices

    def clean(self):
        form_data = self.cleaned_data

        if form_data["responsable"] == form_data["persona"]:
            self._errors["responsable"] = ["El responsable no puede ser igual a la persona"]

        if len(form_data["recurso"]) == 0:
            self._errors["recurso"] = ["Debe seleccionar al menos un recurso"]

        return form_data

bodega/apps/recursos/views.py
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse_lazy,reverse
from django.views.generic import FormView
from django.views.generic.edit import CreateView, UpdateView
from django.views.generic.detail import DetailView
from django.contrib.auth.mixins import LoginRequiredMixin

from django.shortcuts import redirect
from django.http import JsonResponse
from .models import *
from .forms import *


class RegistrarCategoria(LoginRequiredMixin,SuccessMessageMixin,CreateView):
    model = CategoriaRecurso
    form_class = CategoriaForm
    template_name = 'categoria.html'
    success_url = reverse_lazy('recursos:registrar_categoria')
    success_message = "Se ha registrado exitosamente la categoría "

    def get_context_data(self, **kwargs):
        context = super(RegistrarCategoria,self).get_context_data()
        context['titulo'] = 'Registrar categorias para recursos'
        context['lista_categorias'] = CategoriaRecurso.objects.all()
        return context


class EditarCategoria(LoginRequiredMixin,SuccessMessageMixin,UpdateView):
    model = CategoriaRecurso
    form_class = CategoriaForm
    template_name = 'categoria.html'
    success_url = reverse_lazy('recursos:registrar_categoria')
    success_message = "Se ha editado exitosamente la categoría "

    def get_context_data(self, **kwargs):
        context = super(EditarCategoria,self).get_context_data()
        context['titulo'] = 'Editar categoría para recursos'
        context['lista_categorias'] = CategoriaRecurso.objects.all()
        return context


class RegistrarMarca(LoginRequiredMixin,SuccessMessageMixin,CreateView):
    model = MarcaRecurso
    form_class = MarcaForm
    template_name = 'marcas.html'
    success_url = reverse_lazy('recursos:registrar_marca')
    success_message = "Se ha registrado exitosamente la marca "

    def get_context_data(self, **kwargs):
        context = super(RegistrarMarca,self).get_context_data()
        context['titulo'] = 'Registrar marcas para recursos'
        context['lista_marcas'] = MarcaRecurso.objects.all()
        return context


class EditarMarca(LoginRequiredMixin,SuccessMessageMixin,UpdateView):
    model = MarcaRecurso
    form_class = MarcaForm
    template_name = 'marcas.html'
    success_url = reverse_lazy('recursos:registrar_marca')
    success_message = "Se ha editado exitosamente la marca "

    def get_context_data(self, **kwargs):
        context = super(EditarMarca,self).get_context_data()
        context['titulo'] = 'Editar marca para recursos'
        context['lista_marcas'] = MarcaRecurso.objects.all()
        return context


class RegistrarRecurso(LoginRequiredMixin,SuccessMessageMixin,CreateView):
    model = Recurso
    form_class = RecursoForm
    template_name = 'recursos.html'
    success_url = reverse_lazy('recursos:registrar_recurso')
    success_message = "Se ha registrado exitosamente el recurso"

    def get_context_data(self, **kwargs):
        context = super(RegistrarRecurso,self).get_context_data()
        context['titulo'] = 'Registrar recursos'
        context['lista_recursos'] = Recurso.objects.all()
        return context


class EditarRecurso(LoginRequiredMixin,SuccessMessageMixin,UpdateView):
    model = Recurso
    form_class = RecursoForm
    template_name = 'recursos.html'
    success_url = reverse_lazy('recursos:registrar_recurso')
    success_message = "Se ha editado exitosamente el recurso "

    def get_context_data(self, **kwargs):
        context = super(EditarRecurso,self).get_context_data()
        context['titulo'] = 'Editar recurso'
        context['lista_recursos'] = Recurso.objects.all()
        return context


class DetalleRecurso(LoginRequiredMixin,SuccessMessageMixin,DetailView):
    model = Recurso
    template_name = 'detalle_recurso.html'
    context_object_name = 'recurso'

    def get_context_data(self, **kwargs):
        context = super(DetalleRecurso,self).get_context_data()
        context['titulo'] = 'Detalles de recurso'
        context['lista_recursos'] = Recurso.objects.all()
        return context


class AsignarRecursoVarios(LoginRequiredMixin,SuccessMessageMixin,FormView):
    form_class = AsignacionVariosRecursosForm
    template_name = 'asignaciones.html'
    success_url = reverse_lazy('recursos:asignar_varios_recursos')
    success_message = "Se ha registrado exitosamente los recursos"

    def get_form_kwargs(self):
        kwargs = super(AsignarRecursoVarios, self).get_form_kwargs()
        kwargs['request'] = self.request
        no_asignados = []
        try:

            asignaciones=AsignacionRecurso.objects.filter(esta_asignado=True).values_list('recurso_id')
            recursos= Recurso.objects.exclude(id__in=asignaciones).values_list('id')
            no_asignados = recursos
        except Exception:
            pass
        kwargs['no_asignados'] = no_asignados
        return kwargs

    def form_valid(self, form):
        recursos_id = form.cleaned_data['recurso']
        persona = form.cleaned_data['persona']
        print(recursos_id,persona)
        for recurso in Recurso.objects.filter(id__in=recursos_id):
            nueva_asignacion =  AsignacionRecurso(recurso=recurso,persona=persona)
            nueva_asignacion.save()

        return super(AsignarRecursoVarios, self).form_valid(form)

    def get_context_data(self, **kwargs):
        context = super(AsignarRecursoVarios,self).get_context_data()
        context['titulo'] = 'Asignar recursos'
        context['lista_recursos'] = Recurso.objects.all()
        return context



def obtener_recursos(request):
    responsable = request.GET.get('responsable')
    recursos = Recurso.objects.none()
    options = ''
    if responsable:
        asignaciones= AsignacionRecurso.objects.filter(persona=responsable,esta_asignado=True).values_list('recurso_id')
        recursos = Recurso.objects.filter(id__in=asignaciones)
        print(asignaciones,recursos)
    for recurso in recursos:
        options += '<option value="%s">%s</option>' % (
            recurso.id, '(%s) %s' % (recurso.codigo, recurso.nombre)
        )
    response = {}
    response['recursos'] = options
    return JsonResponse(response)


class TrasladarRecursos(LoginRequiredMixin,SuccessMessageMixin,FormView):
    form_class = TrasladoRecursoForm
    template_name = 'trasladar_recursos.html'
    success_url = reverse_lazy('recursos:asignar_varios_recursos')
    success_message = "Se han trasladado exitosamente los recursos"

    def get_form_kwargs(self):
        kwargs = super(TrasladarRecursos, self).get_form_kwargs()
        kwargs['request'] = self.request
        no_asignados = []
        try:

            asignaciones=AsignacionRecurso.objects.filter(esta_asignado=True).values_list('recurso_id')
            recursos= Recurso.objects.exclude(id__in=asignaciones).values_list('id')
            no_asignados = recursos
        except Exception:
            pass
        kwargs['no_asignados'] = no_asignados
        return kwargs

    def form_valid(self, form):
        recursos_id = form.cleaned_data['recurso']
        responsable = form.cleaned_data['responsable']
        persona = form.cleaned_data['persona']
        for recurso in Recurso.objects.filter(id__in=recursos_id):
            asignacion_antigua=AsignacionRecurso.objects.get(recurso=recurso,persona=responsable)
            asignacion_antigua.esta_asignado=False
            asignacion_antigua.save()
            nueva_asignacion = AsignacionRecurso(recurso=recurso,persona=persona)
            nueva_asignacion.save()
        print(recursos_id,persona)

        return super(TrasladarRecursos, self).form_valid(form)

    def get_context_data(self, **kwargs):
        context = super(TrasladarRecursos,self).get_context_data()
        context['titulo'] = 'Trasladar recursos'
        context['lista_recursos'] = Recurso.objects.all()
        return context

@login_required
def retirar_recurso(request,pk):
    persona_id = ''
    try:
        asignacion = AsignacionRecurso.objects.get(recurso__id=pk,esta_asignado=True)
        persona_id = asignacion.persona_id
        asignacion.esta_asignado=False
        asignacion.save()

    except Exception as e:
        print('exception: ', e)
    messages.success(request, "Se ha retirado exitosamente el recurso")
    return redirect(reverse('personal:ver_recursos_personal', kwargs={'pk': persona_id}))

bodega/apps/recursos/templates/asignaciones.html
{% extends "base.html" %}
{% load staticfiles %}
{% load bootstrap3 %}

{% block titulo %}
    {{ titulo }}
{% endblock titulo %}
{% block css %}
{% endblock %}
{% block titulo_pagina %}
    {{ titulo }}
{% endblock titulo_pagina %}

{% block miga_pan %}
    <li class="breadcrumb-item active">Inicio</li>
{% endblock miga_pan %}
{% block regreso %}
    <li><a class="btn btn-sm btn-primary" href="{% url 'usuarios:dashboard' %}">Regresar</a></li>
{% endblock regreso %}

{% block contenido_pagina %}

    <div class="row">
        <div class="col-lg-6 ">
            <!-- Default box -->
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">{{ titulo }}</h3>
                </div>
                <!-- /.box-header -->
                <!-- form start -->
                <form role="form" method="post" enctype="multipart/form-data">{% csrf_token %}
                    <div class="box-body">
                        <div class="form-group">
                            {% bootstrap_form form %}
                        </div>

                    </div>
                    <!-- /.box-body -->

                    <div class="box-footer">
                        <button type="submit" class="btn btn-primary">Registrar</button>
                        <a href="{% url  'usuarios:dashboard'%}" class="btn btn-default">Cancelar</a>
                    </div>
                </form>
            </div>
            <!-- /.box -->

        </div>

    </div>



{% endblock %}
{% block js %}

{% endblock %}
    

bodega/apps/recursos/templates/categoria.html
{% extends "base.html" %}
{% load staticfiles %}
{% load bootstrap3 %}

{% block titulo %}
    {{ titulo }}
{% endblock titulo %}
{% block css %}
{% endblock %}
{% block titulo_pagina %}
    {{ titulo }}
{% endblock titulo_pagina %}

{% block miga_pan %}
    <li class="breadcrumb-item active">Inicio</li>
{% endblock miga_pan %}
{% block regreso %}
    <li><a class="btn btn-sm btn-primary" href="{% url 'usuarios:dashboard' %}">Regresar</a></li>
{% endblock regreso %}

{% block contenido_pagina %}

    <div class="row">
        <div class="col-lg-6 ">
            <!-- Default box -->
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">{{ titulo }}</h3>
                </div>
                <!-- /.box-header -->
                <!-- form start -->
                <form role="form" method="post" enctype="multipart/form-data">{% csrf_token %}
                    <div class="box-body">
                        <div class="form-group">
                            {% bootstrap_form form %}
                        </div>

                    </div>
                    <!-- /.box-body -->

                    <div class="box-footer">
                        <button type="submit" class="btn btn-primary">Registrar</button>
                        <a href="{% url  'recursos:registrar_categoria'%}" class="btn btn-default">Cancelar</a>
                    </div>
                </form>
            </div>
            <!-- /.box -->

        </div>
        <div class="col-lg-6 ">
            <!-- Default box -->
            <div class="box">
                <div class="box-header">
                    <h3 class="box-title">Lista de categorias</h3>
                </div>
                <!-- /.box-header -->
                <div class="box-body">
                    <table id="example1" class="table table-bordered table-striped dataTable">
                        <thead>
                        <tr>
                            <th>Nombre</th>
                            <th>Opciones</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for categoria in lista_categorias %}
                            <tr>
                                <td>{{ categoria }}</td>
                                <td>
                                    <a class="btn btn-warning" href="{% url 'recursos:editar_categoria' categoria.pk %}">Editar</a>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
                <!-- /.box-body -->
            </div>

        </div>
    </div>



{% endblock %}
{% block js %}

{% endblock %}
    

bodega/apps/recursos/templates/detalle_recurso.html
{% extends "base.html" %}
{% load staticfiles %}
{% load bootstrap3 %}

{% block titulo %}
    {{ titulo }}
{% endblock titulo %}
{% block css %}
{% endblock %}
{% block titulo_pagina %}
    {{ titulo }}
{% endblock titulo_pagina %}

{% block miga_pan %}
    <li class="breadcrumb-item active">Inicio</li>
{% endblock miga_pan %}
{% block regreso %}
    <li><a class="btn btn-sm btn-primary" href="{% url 'usuarios:dashboard' %}">Regresar</a></li>
{% endblock regreso %}

{% block contenido_pagina %}

    <div class="row">
        <div class="col-lg-4 ">
            <!-- Default box -->
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">Detalles del recurso</h3>
                </div>
                <div class="box-body">
                    <h4>Código-Nombre:<small>{{ recurso }}</small></h4>
                    <h4>Descripción:<small>{{ recurso.descripcion }}</small></h4>
                    <h4>Marca:<small>{{ recurso.marca }}</small></h4>
                    <h4>Categoría:<small>{{ recurso.categoria }}</small></h4>
                </div>


            </div>
            <!-- /.box -->

        </div>
        <div class="col-lg-8 ">
            <!-- Default box -->
            <div class="box">
                <div class="box-header">
                    <h3 class="box-title">Historial de asignaciones</h3>
                </div>
                <!-- /.box-header -->
                <div class="box-body">
                    <table id="example1" class="table table-bordered table-striped dataTable">
                        <thead>
                        <tr>
                            <th>Responsable</th>
                            <th>Fecha</th>
                            <th>Estado</th>

                        </tr>
                        </thead>
                        <tbody>
                        {% for asignacion in recurso.asignaciones.all %}
                            <tr>
                                <td>{{ asignacion.persona }}</td>
                                <td>{{ asignacion.fecha }}</td>
                                <td>
                                    {% if asignacion.esta_asignado %}
                                        <span class="label label-success">Asignado</span>
                                    {% else %}
                                        <span class="label label-warning">No asignado</span>
                                    {% endif %}

                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
                <!-- /.box-body -->
            </div>

        </div>
    </div>



{% endblock %}
{% block js %}

{% endblock %}
    

bodega/apps/recursos/templates/marcas.html
{% extends "base.html" %}
{% load staticfiles %}
{% load bootstrap3 %}

{% block titulo %}
    {{ titulo }}
{% endblock titulo %}
{% block css %}
{% endblock %}
{% block titulo_pagina %}
    {{ titulo }}
{% endblock titulo_pagina %}

{% block miga_pan %}
    <li class="breadcrumb-item active">Inicio</li>
{% endblock miga_pan %}
{% block regreso %}
    <li><a class="btn btn-sm btn-primary" href="{% url 'usuarios:dashboard' %}">Regresar</a></li>
{% endblock regreso %}

{% block contenido_pagina %}

    <div class="row">
        <div class="col-lg-6 ">
            <!-- Default box -->
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">{{ titulo }}</h3>
                </div>
                <!-- /.box-header -->
                <!-- form start -->
                <form role="form" method="post" enctype="multipart/form-data">{% csrf_token %}
                    <div class="box-body">
                        <div class="form-group">
                            {% bootstrap_form form %}
                        </div>

                    </div>
                    <!-- /.box-body -->

                    <div class="box-footer">
                        <button type="submit" class="btn btn-primary">Registrar</button>
                        <a href="{% url  'recursos:registrar_marca'%}" class="btn btn-default">Cancelar</a>
                    </div>
                </form>
            </div>
            <!-- /.box -->

        </div>
        <div class="col-lg-6 ">
            <!-- Default box -->
            <div class="box">
                <div class="box-header">
                    <h3 class="box-title">Lista de marcas</h3>
                </div>
                <!-- /.box-header -->
                <div class="box-body">
                    <table id="example1" class="table table-bordered table-striped dataTable">
                        <thead>
                        <tr>
                            <th>Nombre</th>
                            <th>Descripción</th>
                            <th>Opciones</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for marca in lista_marcas %}
                            <tr>
                                <td>{{ marca }}</td>
                                <td>{{ marca.descripcion }}</td>
                                <td>
                                    <a class="btn btn-warning" href="{% url 'recursos:editar_marca' marca.pk %}">Editar</a>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
                <!-- /.box-body -->
            </div>

        </div>
    </div>



{% endblock %}
{% block js %}

{% endblock %}
    

bodega/apps/recursos/templates/recursos.html
{% extends "base.html" %}
{% load staticfiles %}
{% load bootstrap3 %}

{% block titulo %}
    {{ titulo }}
{% endblock titulo %}
{% block css %}
{% endblock %}
{% block titulo_pagina %}
    {{ titulo }}
{% endblock titulo_pagina %}

{% block miga_pan %}
    <li class="breadcrumb-item active">Inicio</li>
{% endblock miga_pan %}
{% block regreso %}
    <li><a class="btn btn-sm btn-primary" href="{% url 'usuarios:dashboard' %}">Regresar</a></li>
{% endblock regreso %}

{% block contenido_pagina %}

    <div class="row">
        <div class="col-lg-4 ">
            <!-- Default box -->
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">{{ titulo }}</h3>
                </div>
                <!-- /.box-header -->
                <!-- form start -->
                <form role="form" method="post" enctype="multipart/form-data">{% csrf_token %}
                    <div class="box-body">
                        <div class="form-group">
                            {% bootstrap_form form %}
                        </div>

                    </div>
                    <!-- /.box-body -->

                    <div class="box-footer">
                        <button type="submit" class="btn btn-primary">Registrar</button>
                        <a href="{% url  'recursos:registrar_recurso'%}" class="btn btn-default">Cancelar</a>
                    </div>
                </form>
            </div>
            <!-- /.box -->

        </div>
        <div class="col-lg-8 ">
            <!-- Default box -->
            <div class="box">
                <div class="box-header">
                    <h3 class="box-title">Lista de recursos</h3>
                </div>
                <!-- /.box-header -->
                <div class="box-body">
                    <table id="example1" class="table table-bordered table-striped dataTable">
                        <thead>
                        <tr>
                            <th>Nombre</th>
                            <th>Descripción</th>
                            <th>Opciones</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for recurso in lista_recursos %}
                            <tr>
                                <td>{{ recurso }}</td>
                                <td>{{ recurso.descripcion }}</td>
                                <td>
                                    <a class="btn btn-info" href="{% url 'recursos:detalle_recurso' recurso.pk %}">Detalles</a>
                                    <a class="btn btn-warning" href="{% url 'recursos:editar_recurso' recurso.pk %}">Editar</a>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
                <!-- /.box-body -->
            </div>

        </div>
    </div>



{% endblock %}
{% block js %}

{% endblock %}
    

bodega/apps/recursos/templates/trasladar_recursos.html
{% extends "base.html" %}
{% load staticfiles %}
{% load bootstrap3 %}

{% block titulo %}
    {{ titulo }}
{% endblock titulo %}
{% block css %}
{% endblock %}
{% block titulo_pagina %}
    {{ titulo }}
{% endblock titulo_pagina %}

{% block miga_pan %}
    <li class="breadcrumb-item active">Inicio</li>
{% endblock miga_pan %}
{% block regreso %}
    <li><a class="btn btn-sm btn-primary" href="{% url 'usuarios:dashboard' %}">Regresar</a></li>
{% endblock regreso %}

{% block contenido_pagina %}

    <div class="row">
        <div class="col-lg-6 ">
            <!-- Default box -->
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">{{ titulo }}</h3>
                </div>
                <!-- /.box-header -->
                <!-- form start -->
                <form role="form" method="post" enctype="multipart/form-data">{% csrf_token %}
                    <div class="box-body">
                        <div class="form-group">
                            {% bootstrap_form form %}
                        </div>

                    </div>
                    <!-- /.box-body -->

                    <div class="box-footer">
                        <button type="submit" class="btn btn-primary">Registrar</button>
                        <a href="{% url  'recursos:registrar_recurso'%}" class="btn btn-default">Cancelar</a>
                    </div>
                </form>
            </div>
            <!-- /.box -->

        </div>

    </div>



{% endblock %}
{% block js %}
    <script type="text/javascript">
        // Funcion que filtra las opciones  del selecttor de escuelas
        $(document).ready(function() {
            $("#id_responsable").on("change", getRecursos);
        });

        function getRecursos() {
            var responsable = $("#id_responsable").val();

            if (responsable) {
                // Eliminamos las opciones anteriores del select

                $("#id_recurso").html("");
                var request = $.ajax({
                    type: "GET",
                    url: "{% url 'recursos:obtener_recursos' %}",
                    data: {
                        "responsable": responsable,
                    },
                });
                request.done(function(response) {
                    // Agregamos los resultados al select

                    $("#id_recurso").html(response.recursos);
                    $("#id_recurso").trigger("change");
                });
            } else {
                $("#id_recurso").html("<option value='' selected='selected'>---------</option>");
                $("#id_recurso").trigger("change");
            }
        }
    </script>
{% endblock %}
    